services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit-lab
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
  
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto-lab
    ports:
      - "1883:1883"
    restart: unless-stopped
